name: 'pulse-event'
description: 'sends events to pulse resources'
author: 'elisasre'
inputs:
  componentid: 
    required: true
    description: 'id of resource in pulse'
  type:
    required: true
    description: 'deployment or incident'
  message:
    required: true
    description: 'additional information about event'
  canary:
    required: false
    default: 'false'
    description: 'target pulse canary environment'
runs:
  using: 'node20'
  main: 'dist/index.js'
